---
title: "TFM"
author: "Yosri"
date: "22/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
```


Maintenant on va ajouter la  Prediction, et on va voir les Graphes 

## Merluza NORTH


```{r echo=FALSE, message=FALSE, warning=FALSE}

# Read data
Database<-read.csv("Hake.csv",header = TRUE, sep= ";", encoding="UTF-8")
z<-subset(Database, Database[,17] == "hke.27.3a46-8abd")
df <- data.frame(x = z$SSB, y = z$SP)
# Fit model
model <- nls(y~a*x + b*x^2, start=list(a=1.4, b=-0.0000226), data=df)
summary(model)
# Predict figures
av <- seq(0, max(z$SSB)*1.5, by=100)
bv <- predict(model, newdata=(list(x=av)))       # the mane must be "x", as in the model
# Plot
xMax <- max(av[max(which(bv>0))+1], max(z$SSB))  # maximun Biomass for plots
a <- seq(length(z$SSB) - 1)
Firstyea<-subset(z, z[,1] == "1978")
Lastyea<-subset(z, z[,1] == "2018")
plot(z$SSB, z$SP, pch=15,  xlab="ssb", ylab="Surplus Production",xlim=c(0, xMax), ylim=c(0, max(bv)*1.2),type="b", col="red")
arrows(z$SSB[a], z$SP[a], z$SSB[a + 1], z$SP[a + 1],length = 0.1,col="black", angle = 10) 
points(Firstyea$SSB,Firstyea$SP,pch = 21, cex=2, col="blue",bg="blue",lwd=2)
points(Lastyea$SSB,Lastyea$SP,pch = 24, cex=2, col="blue",bg="blue",lwd=2)

lines(av, bv, col="red", type="l")
```



##    Merluza Sur

```{r echo=FALSE, message=FALSE, warning=FALSE}
# Read data
Database<-read.csv("Hake.csv",header = TRUE, sep= ";", encoding="UTF-8")
z<-subset(Database, Database[,17] == "hke.27.8c9a")
df <- data.frame(x = z$SSB, y = z$SP)
# Fit model
model <- nls(y~a*x + b*x^2, start=list(a=1.4, b=-0.0000226), data=df)
summary(model)
# Predict figures
av <- seq(0, max(z$SSB)*1.5, by=100)
bv <- predict(model, newdata=(list(x=av)))       # the mane must be "x", as in the model
# Plot
xMax <- max(av[max(which(bv>0))+1], max(z$SSB))  # maximun Biomass for plots
a <- seq(length(z$SSB) - 1)
Firstyea<-subset(z, z[,1] == "1982")
Lastyea<-subset(z, z[,1] == "2018")
plot(z$SSB, z$SP, pch=15,  xlab="ssb", ylab="Surplus Production",xlim=c(0, xMax), ylim=c(0, max(bv)*1.2),type="b", col="red")
arrows(z$SSB[a], z$SP[a], z$SSB[a + 1], z$SP[a + 1],length = 0.1,col="black", angle = 10) 
points(Firstyea$SSB,Firstyea$SP,pch = 21, cex=2, col="blue",bg="blue",lwd=2)
points(Lastyea$SSB,Lastyea$SP,pch = 24, cex=2, col="blue",bg="blue",lwd=2)

lines(av, bv, col="red", type="l")



```

# Anglerfish

## ANGFISH NORTH


```{r echo=FALSE, message=FALSE, warning=FALSE}
# Read data


setwd("C:/Users/zanni/Desktop/TFM/TFMYosri")
Database<-read.csv("Anglerfish.csv",header = TRUE, sep= ";", encoding="UTF-8")

z<-subset(Database, Database[,17] == "mon.27.78abd")
df <- data.frame(x = z$SSB, y = z$SP)


# Fit model
model <- nls(y~a*x + b*x^2, start=list(a=1.4, b=-0.0000226), data=df)
summary(model)
# Predict figures
av <- seq(0, max(z$SSB)*1.5, by=100)
bv <- predict(model, newdata=(list(x=av)))       # the mane must be "x", as in the model
# Plot
xMax <- max(av[max(which(bv>0))+1], max(z$SSB))  # maximun Biomass for plots
a <- seq(length(z$SSB) - 1)
Firstyea<-subset(z, z[,1] == "1986")
Lastyea<-subset(z, z[,1] == "2018")
plot(z$SSB, z$SP, pch=15,  xlab="ssb", ylab="Surplus Production",xlim=c(0, xMax), ylim=c(0, max(bv)*1.5),type="b", col="red")
arrows(z$SSB[a], z$SP[a], z$SSB[a + 1], z$SP[a + 1],length = 0.1,col="black", angle = 10) 
points(Firstyea$SSB,Firstyea$SP,pch = 21, cex=2, col="blue",bg="blue",lwd=2)
points(Lastyea$SSB,Lastyea$SP,pch = 24, cex=2, col="blue",bg="blue",lwd=2)

lines(av, bv, col="red", type="l")

```

## ANGFISH Sur

```{r echo=FALSE, message=FALSE, warning=FALSE}
# Read data

setwd("C:/Users/zanni/Desktop/TFM/TFMYosri")
Database<-read.csv("Anglerfish.csv",header = TRUE, sep= ";", encoding="UTF-8")

z<-subset(Database, Database[,17] == "mon.27.8c9a")
df <- data.frame(x = z$SSB, y = z$SP)


# Fit model
model <- nls(y~a*x + b*x^2, start=list(a=1.4, b=-0.0000226), data=df)
summary(model)
# Predict figures
av <- seq(0, max(z$SSB)*1.5, by=100)
bv <- predict(model, newdata=(list(x=av)))       # the mane must be "x", as in the model
# Plot
xMax <- max(av[max(which(bv>0))], max(z$SSB))  # maximun Biomass for plots
a <- seq(length(z$SSB) - 1)
Firstyea<-subset(z, z[,1] == "1980")
Lastyea<-subset(z, z[,1] == "2018")
plot(z$SSB, z$SP, pch=15,  xlab="ssb", ylab="Surplus Production",xlim=c(0, xMax), ylim=c(-3000, max(bv)*3.9),type="b", col="red")
arrows(z$SSB[a], z$SP[a], z$SSB[a + 1], z$SP[a + 1],length = 0.1,col="black", angle = 10) 
points(Firstyea$SSB,Firstyea$SP,pch = 21, cex=2, col="blue",bg="blue",lwd=2)
points(Lastyea$SSB,Lastyea$SP,pch = 24, cex=2, col="blue",bg="blue",lwd=2)

lines(av, bv, col="red", type="l")

```


# SARDINE

## SARDINE NORTH

```{r echo=FALSE, message=FALSE, warning=FALSE}
# Read data


setwd("C:/Users/zanni/Desktop/TFM/TFMYosri")
Database<-read.csv("Sardine.csv",header = TRUE, sep= ";", encoding="UTF-8")

z<-subset(Database, Database[,17] == "pil.27.8abd")
df <- data.frame(x = z$SSB, y = z$SP)


# Fit model
model <- nls(y~a*x + b*x^2, start=list(a=1.4, b=-0.0000226), data=df)
summary(model)
# Predict figures
av <- seq(0, max(z$SSB)*1.5, by=100)
bv <- predict(model, newdata=(list(x=av)))       # the mane must be "x", as in the model
# Plot
xMax <- max(av[max(which(bv>0))+1], max(z$SSB))  # maximun Biomass for plots
a <- seq(length(z$SSB) - 1)
Firstyea<-subset(z, z[,1] == "2000")
Lastyea<-subset(z, z[,1] == "2018")
plot(z$SSB, z$SP, pch=15,  xlab="ssb", ylab="Surplus Production",xlim=c(0, xMax), ylim=c(-13000, max(bv)*1.8),type="b", col="red")
arrows(z$SSB[a], z$SP[a], z$SSB[a + 1], z$SP[a + 1],length = 0.1,col="black", angle = 10) 
points(Firstyea$SSB,Firstyea$SP,pch = 21, cex=2, col="blue",bg="blue",lwd=2)
points(Lastyea$SSB,Lastyea$SP,pch = 24, cex=2, col="blue",bg="blue",lwd=2)

lines(av, bv, col="red", type="l")
```

## SARDINE Sur

```{r echo=FALSE, message=FALSE, warning=FALSE}
setwd("C:/Users/zanni/Desktop/TFM/TFMYosri")
Database<-read.csv("Sardine.csv",header = TRUE, sep= ";", encoding="UTF-8")

z<-subset(Database, Database[,17] == "pil.27.8c9a")
df <- data.frame(x = z$SSB, y = z$SP)


# Fit model
model <- nls(y~a*x + b*x^2, start=list(a=1.4, b=-0.0000226), data=df)
summary(model)
# Predict figures
av <- seq(0, max(z$SSB)*1.5, by=100)
bv <- predict(model, newdata=(list(x=av)))       # the mane must be "x", as in the model
# Plot
xMax <- max(av[max(which(bv>0))+1], max(z$SSB))  # maximun Biomass for plots
a <- seq(length(z$SSB) - 1)
Firstyea<-subset(z, z[,1] == "1978")
Lastyea<-subset(z, z[,1] == "2019")
plot(z$SSB, z$SP, pch=15,  xlab="ssb", ylab="Surplus Production",xlim=c(0, xMax), ylim=c(-51000, max(bv)*4),type="b", col="red")
arrows(z$SSB[a], z$SP[a], z$SSB[a + 1], z$SP[a + 1],length = 0.1,col="black", angle = 10) 
points(Firstyea$SSB,Firstyea$SP,pch = 21, cex=2, col="blue",bg="blue",lwd=2)
points(Lastyea$SSB,Lastyea$SP,pch = 24, cex=2, col="blue",bg="blue",lwd=2)

lines(av, bv, col="red", type="l")
```

# Megrim

## Megrim NORTH

```{r echo=FALSE, message=FALSE, warning=FALSE}

# Read data


setwd("C:/Users/zanni/Desktop/TFM/TFMYosri")
Database<-read.csv("Megrim3.csv",header = TRUE, sep= ";", encoding="UTF-8")

z<-subset(Database, Database[,17] == "meg.27.7b-k8abd")
df <- data.frame(x = z$SSB, y = z$SP)


# Fit model
model <- nls(y~a*x + b*x^2, start=list(a=1.4, b=-0.0000226), data=df)
summary(model)
# Predict figures
av <- seq(0, max(z$SSB)*1.5, by=100)
bv <- predict(model, newdata=(list(x=av)))       # the mane must be "x", as in the model
# Plot
xMax <- max(av[max(which(bv>0))+1], max(z$SSB))  # maximun Biomass for plots
a <- seq(length(z$SSB) - 1)
Firstyea<-subset(z, z[,1] == "1984")
Lastyea<-subset(z, z[,1] == "2018")
plot(z$SSB, z$SP, pch=15,  xlab="ssb", ylab="Surplus Production",xlim=c(0, xMax), ylim=c(0, max(bv)*2.2),type="b", col="red")
arrows(z$SSB[a], z$SP[a], z$SSB[a + 1], z$SP[a + 1],length = 0.1,col="black", angle = 10) 
points(Firstyea$SSB,Firstyea$SP,pch = 21, cex=2, col="blue",bg="blue",lwd=2)
points(Lastyea$SSB,Lastyea$SP,pch = 24, cex=2, col="blue",bg="blue",lwd=2)

lines(av, bv, col="red", type="l")


```

## Megrim Sur

```{r echo=FALSE, message=FALSE, warning=FALSE}

# Read data


setwd("C:/Users/zanni/Desktop/TFM/TFMYosri")
Database<-read.csv("Megrim3.csv",header = TRUE, sep= ";", encoding="UTF-8")

z<-subset(Database, Database[,17] == "meg.27.8c9a")
df <- data.frame(x = z$SSB, y = z$SP)


# Fit model
model <- nls(y~a*x + b*x^2, start=list(a=1.4, b=-0.0000226), data=df)
summary(model)
# Predict figures
av <- seq(0, max(z$SSB)*1.5, by=100)
bv <- predict(model, newdata=(list(x=av)))       # the mane must be "x", as in the model
# Plot
xMax <- max(av[max(which(bv>0))], max(z$SSB))  # maximun Biomass for plots
a <- seq(length(z$SSB) - 1)
Firstyea<-subset(z, z[,1] == "1986")
Lastyea<-subset(z, z[,1] == "2018")
plot(z$SSB, z$SP, pch=15,  xlab="ssb", ylab="Surplus Production",xlim=c(0, xMax), ylim=c(0, max(bv)*2.2),type="b", col="red")
arrows(z$SSB[a], z$SP[a], z$SSB[a + 1], z$SP[a + 1],length = 0.1,col="black", angle = 10) 
points(Firstyea$SSB,Firstyea$SP,pch = 21, cex=2, col="blue",bg="blue",lwd=2)
points(Lastyea$SSB,Lastyea$SP,pch = 24, cex=2, col="blue",bg="blue",lwd=2)

lines(av, bv, col="red", type="l")


```

