setwd("C:/Users/zanni/Desktop/TFM")
Database <- read.csv(file.choose("HAKESOTH"), header = TRUE, sep= ";", encoding="UTF-8")
summary(Database) 
dim(Database)
install.packages("ggplot2")
library("ggplot2")
ggplot(Database, aes(x = A.f1.o, y = Bio , )) + geom_point()+ geom_smooth()
ggplot(Database, aes(x = A.f1.o, y = Btrend , )) + geom_point()+ geom_smooth()
ggplot(Database, aes(x = A.f1.o, y = BvB , )) + geom_point()+ geom_smooth()
ggplot(Database, aes(x = A.f1.o, y = BvT , )) + geom_point()+ geom_smooth()
ggplot(Database, aes(x = A.f1.o, y = CPUE , )) + geom_point()+ geom_smooth()
ggplot(Database, aes(x = A.f1.o, y = Ctrend , )) + geom_point()+ geom_smooth()
ggplot(Database, aes(x = A.f1.o, y = CvMEANC  , )) + geom_point()+ geom_smooth()
ggplot(Database, aes(x = A.f1.o, y = CvMSY , )) + geom_point()+ geom_smooth()
ggplot(Database, aes(x = A.f1.o, y = FF  , )) + geom_point()+ geom_smooth()
ggplot(Database, aes(x = A.f1.o, y = MCatch , )) + geom_point()+ geom_smooth()
ggplot(Database, aes(x = A.f1.o, y = R , )) + geom_point()+ geom_smooth()
ggplot(Database, aes(x = A.f1.o, y = SSB          , )) + geom_point()+ geom_smooth()
ggplot(Database, aes(x = A.f1.o, y = Survey , )) + geom_point()+ geom_smooth()
ggplot(Database, aes(x = A.f1.o, y = U  , )) + geom_point()+ geom_smooth()
ggplot(Database, aes(x = A.f1.o, y = Utrend , )) + geom_point()+ geom_smooth()
ggplot(Database, aes(x = A.f1.o, y = UvT , )) + geom_point()+ geom_smooth()



